# Generated by Django 3.2 on 2021-12-21 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mocktest', '0001_initial'),
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testwishlist',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktest.mocktest'),
        ),
        migrations.AddField(
            model_name='testwishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testset',
            name='mocktest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktest.mocktest'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='mocktest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktest.mocktest'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='testset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktest.testset'),
        ),
        migrations.AddField(
            model_name='testcart',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktest.mocktest'),
        ),
        migrations.AddField(
            model_name='testcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mytestset',
            name='testset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktest.testset'),
        ),
        migrations.AddField(
            model_name='mytestset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mymocktest',
            name='mocktest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktest.mocktest'),
        ),
        migrations.AddField(
            model_name='mymocktest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mocktestrating',
            name='mocktest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktest.mocktest'),
        ),
        migrations.AddField(
            model_name='mocktestrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category'),
        ),
        migrations.AlterUniqueTogether(
            name='mocktestrating',
            unique_together={('user', 'mocktest')},
        ),
        migrations.AlterIndexTogether(
            name='mocktestrating',
            index_together={('user', 'mocktest')},
        ),
    ]
