# Generated by Django 4.0.1 on 2022-01-10 05:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mocktest', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mytestset',
            unique_together={('user', 'testset')},
        ),
        migrations.AlterUniqueTogether(
            name='usertest',
            unique_together={('testset', 'question')},
        ),
        migrations.AlterIndexTogether(
            name='mytestset',
            index_together={('user', 'testset')},
        ),
        migrations.AlterIndexTogether(
            name='usertest',
            index_together={('testset', 'question')},
        ),
    ]
