# Generated by Django 4.0.1 on 2022-01-10 06:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mocktest', '0003_alter_mytestset_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertest',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='usertest',
            index_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usertest',
            unique_together={('user', 'testset', 'question')},
        ),
        migrations.AlterIndexTogether(
            name='usertest',
            index_together={('user', 'testset', 'question')},
        ),
    ]
