# Generated by Django 4.0.1 on 2022-01-10 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0005_mytestset_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertest',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='usertest',
            index_together=set(),
        ),
        migrations.AddField(
            model_name='usertest',
            name='mytest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mocktest.mytestset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mytestset',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mytestset',
            name='total_mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='usertest',
            unique_together={('mytest', 'question')},
        ),
        migrations.AlterIndexTogether(
            name='usertest',
            index_together={('mytest', 'question')},
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='testset',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='user',
        ),
    ]
