# Generated by Django 3.2 on 2021-12-23 05:48

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='assignment_file',
            field=models.FileField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='poralekha-bucket'), upload_to='assignment/instructor/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_video',
            field=models.FileField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='poralekha-bucket'), upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='assignment_file',
            field=models.FileField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='poralekha-bucket'), upload_to='assignment/student/'),
        ),
    ]
