"""
Django settings for poralekha project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
# import django_heroku
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i7$9#a^xf1vh)4q^p%$4aa3)1460b8q1$*-*cs9xmvv+iz3j%t'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True
ALLOWED_HOSTS = ['*']
    




# Application definition

INSTALLED_APPS = [
    'channels',
    'chat',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'phonenumber_field',
    'rest_framework',
    'users',
    'app',
    'tutor',
    'mocktest',
    'api',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    'django_summernote',
    'mathfilters',
    'storages',
    
   
    
     
    
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'poralekha.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]


WSGI_APPLICATION = 'poralekha.wsgi.application'
ASGI_APPLICATION = 'poralekha.asgi.application'


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
'default': {
    
    'ENGINE':'django.db.backends.postgresql',
    'NAME': 'dde6ia36gv1tno',
    'USER':'huvgvgxncxqonk',
    'PASSWORD':'b5ee2408cb15c3c53e245fc18fd51e4116bd93aa15d1fa0bb624624a2391fe7e',
    'HOST':'ec2-18-210-118-224.compute-1.amazonaws.com',
    'PORT':'5432',

    


}
}
    

# DATABASES = {
#     'default': {
#         'ENGINE':'django.db.backends.postgresql',
#         'NAME': 'poralekha',
#         'USER':'postgres',
#         'PASSWORD':'6274',
#         'HOST':'localhost',


#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

TEMPLATE_CONTEXT_PROCESSORS= 'django.core.context_processors.request'

ACCOUNT_LOGOUT_ON_GET=True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_ROOT = BASE_DIR/'static'
STATIC_URL = '/static/'
  
MEDIA_URL='/media/'
MEDIA_ROOT=BASE_DIR/'media'
# CLOUDINARY_STORAGE = {
#     'CLOUD_NAME': 'df3ijsjjm',
#     'API_KEY': '889118279281221',
#     'API_SECRET': 'xaj3IMtZx8Y9eUguz3Q-Lq_chpA'
# }
# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

AWS_ACCESS_KEY_ID = 'AKIA2MI7FNENLUFGEAGD'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME  = 'poralekha-bucket'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_S3_REGION_NAME = 'ap-southeast-1'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# STATICFILES_STORAGE = 'django_s3_storage.storage.StaticS3Storage'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

AUTH_USER_MODEL='users.User'
LOGIN_URL='/login'
LOGIN_REDIRECT_URL='/'
LOGOUT_REDIRECT_URL='/'
ACCOUNT_LOGOUT_REDIRECT_URL='/'

EMAIL_FROM_USER = 'info@poralekhaonline.com'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'nasirkhan97.bd@gmail.com'
EMAIL_HOST_PASSWORD = 'uyfzntutibbzyekr'
EMAIL_PORT = 587
# EMAIL_BACKEND='django.core.mail.backends.console.EmailBackend'
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

JAZZMIN_SETTINGS={
     "site_title": "Poralekha Admin",
     "site_header": "Poralekha",
} 

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        
    ),
}

# SIMPLE_JWT = {
#    'AUTH_HEADER_TYPES': ('JWT',),
# }

# DJOSER = {
#     'SET_PASSWORD_RETYPE': True,
#     'PASSWORD_RESET_CONFIRM_RETYPE':True,
#     'PASSWORD_RESET_CONFIRM_URL': 'password/reset/confirm/{uid}/{token}',
#     'ACTIVATION_URL': 'activate/{uid}/{token}',
#     'SEND_ACTIVATION_EMAIL': True,
#     'SERIALIZERS': {
#         'user_create':'users.serializers.UserCreateSerializer',
#         'user':'users.serializers.UserCreateSerializer',
#         'user_delete':'djoser.serializers.UserDeleteSerializer',
#     },
# }

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# google login info
# 303611051005-rrhldt0an53hrffplvriv2csk55ju0bs.apps.googleusercontent.com
# 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
# facebook login info
# 398041581980134
# f1274ca28ba117316a4b07ed7ba909b5
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
            
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },

    'facebook': {
        'METHOD': 'oauth2',
        # 'SDK_URL': '//connect.facebook.net/{locale}/sdk.js',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name'
        ],
        'EXCHANGE_TOKEN': True,
        # 'LOCALE_FUNC': 'path.to.callable',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v7.0',
    }
}

# django_heroku.settings(locals())